#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[ -f $DIR/.notfirstrun ] || cd $DIR && git submodule init && touch $DIR/.notfirstrun
cd $DIR
git pull
git submodule foreach git checkout master && git submodule update

cd $HOME && ln -fs $DIR && ln -fs $DIR/vimrc .vimrc

