#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[ -f $DIR/.notfirstrun ] || cd $DIR && git submodule update --init && touch $DIR/.notfirstrun
cd $DIR
git pull
git submodule foreach git checkout master && git submodule foreach git pull

ln -fns $DIR ~/.vim && ln -fs $DIR/vimrc ~/.vimrc

